export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = ' CART_SAVE_SHIPPING_ADDRESS'
export const CART_EMPTY_ON_PURCHASE = 'CART_EMPTY_ON_PURCHASE'

export const CART_OPEN = 'CART_OPEN'
export const CART_CLOSED = 'CART_CLOSED'
